# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e6877bed194d034e769f207091470aa4fcd526d057fea04a5184688c6ccbc4d0eda339b8d49d7c8af3dd65080de58f1fc611f8891d8099da532e5dbf227f043

test:
  secret_key_base: a5c0b2e0f5c20ff20ce8845ea16c280382516f39e65f76697aa9b4a4d769fa2bfabc7aba52b24a83adafe1d4086fe08d952d46ff7ff8383c984de1fe8470d92b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
